apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: fluxalert
  namespace: flux-system
spec:
  providerRef:
    name: fluxgithubprovider
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: k8snginxappkust
      namespace: flux-system