apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: flux-system
spec:
  encryptedData:
    token: AgBEkOx1Jh1YF0A9HRdyL+jHR5TLawqRDPf8KUMoAhlgBBxsS8ih/qcZI0uqb0SUzqxDaKKzhuaA06vEFfMK5d98rqiA9vFVykXHQY2uHUB3L5gg/g5Ksz1MYZonOk6I8zwfMem+0Mr0vIUdVgNpop3aTTXtXlSvgf5Cgrp3bZ20ZRdPqk2NQrrmz9yNCVRMCR2AvbHQae1xm4TxI2eA9mwn324aLidBygixEy8fRyUw8REvdXvuM6WYhGF76tV+F5KxcXqmNcg3ajazD3gIxSN2sd/1Pn/mVXBL7oqwkjiDuWtYUY5q3qK8c28dlAnV7dfGQwSo3RZPy3RXmvawS2CiSZnBmtepn4MjZzA5K6cyFkkYcwYhVCTmtgN+zOBplPNX2K6dzCwp+jYrXCF0sGdi09Wy/bWblTBBDyYF1jjRrVR9wjiPTfnTay03sbFXwpNBMWm+Dr7NV+OWFk49SMZ1gmcjjw/EYBhQXdO153biSk+IxN9QslnkebgcN4iLxJJI0fZk0E0LitJqoecEk3WR4GV8iNWme5udyhNx5CXN5TnqsAGDVIt/b3fOJULfec3o4JtyZpJdSND8xaEOpISdRBG+/eY/mK1q07HC6ThcHt0TO1Uv/l/B7xR8QLorgy/FcLqFOI9F9Vigf7M9ikJe/zoGmBdJV6XUF/T6hPVjq41dkzfExCZHPqJyTxjm7zgPnXvXd4ivRFwBoTboBpQkdk7cK7t9sMKZBYL6cq20DauX2qcldRjKC/iGSg==
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: flux-system

